spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://localhost:5432/order-service
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update